# Generated by Django 5.2.5 on 2025-09-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_cities_countries_departaments_users_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departaments',
            new_name='Departament',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
