# Generated by Django 5.2.5 on 2025-09-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_id_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.departament'),
            preserve_default=False,
        ),
    ]
