# Generated by Django 5.2.5 on 2025-09-09 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_city_id_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='id_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.country'),
            preserve_default=False,
        ),
    ]
